apiVersion: v1
kind: Namespace
metadata:
  name: udn-test3
  labels:
    udn-cluster: "true"
    k8s.ovn.org/primary-user-defined-network: ""
---
apiVersion: v1
kind: Namespace
metadata:
  name: udn-test4
  labels:
    udn-cluster: "true"
    k8s.ovn.org/primary-user-defined-network: ""
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: cluster-udn-test1
spec:
  namespaceSelector:
    matchLabels:
      udn-cluster: "true"
  network:
    topology: Layer2
    layer2:
      role: Primary
      subnets:
        - "10.100.0.0/16"
