apiVersion: v1
kind: Namespace
metadata:
  name: udn-localnet-test
  labels:
    udn-localnet: "true"
---
apiVersion: k8s.ovn.org/v1
kind: ClusterUserDefinedNetwork
metadata:
  name: localnet-physical
spec:
  namespaceSelector:
    matchLabels:
      udn-localnet: "true"
  network:
    topology: Localnet
    localnet:
      role: Secondary
      physicalNetworkName: localnet1
      ipam:
        lifecycle: Persistent
      subnets:
        - "192.168.1.0/24"
