apiVersion: k8s.ovn.org/v1
kind: UserDefinedNetwork
metadata:
  name: secondary-layer2-udn
  namespace: udn-test1
spec:
  topology: Layer2
  layer2:
    role: Secondary
    subnets:
      - "10.210.0.0/16"
