apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-localnet-1
  namespace: udn-localnet-test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-localnet-1
    spec:
      domain:
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
            - name: localnet-if
              bridge: {}
      networks:
        - name: default
          pod: {}
        - name: localnet-if
          multus:
            networkName: localnet-physical
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              user: demo
              password: redhat
              chpasswd: { expire: false }
              ssh_pwauth: true
