apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-overlap-a
  namespace: udn-overlap-a
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-overlap-a
    spec:
      domain:
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: redhat
              chpasswd: { expire: false }
              ssh_pwauth: true
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-overlap-b
  namespace: udn-overlap-b
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-overlap-b
    spec:
      domain:
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              password: redhat
              chpasswd: { expire: false }
              ssh_pwauth: true
