apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-l2-a
  namespace: udn-test1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-l2-a
    spec:
      domain:
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: demo
                  groups: [wheel]
                  shell: /bin/bash
              chpasswd:
                expire: false
                users:
                  - name: demo
                    password: redhat
              ssh_pwauth: true
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-l2-b
  namespace: udn-test1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-l2-b
    spec:
      domain:
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |
              #cloud-config
              users:
                - name: demo
                  groups: [wheel]
                  shell: /bin/bash
              chpasswd:
                expire: false
                users:
                  - name: demo
                    password: redhat
              ssh_pwauth: true
