apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udn-full-validation
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/awez-sonde/udn-demo.git
    targetRevision: main
    path: part-1-udns/examples
    directory:
      recurse: false
      include: all-validation-vms-only.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: kubevirt.io
      kind: VirtualMachine
      jsonPointers:
        - /spec/running
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
