apiVersion: v1
kind: Service
metadata:
  name: vm-l2-a-service
  namespace: udn-test1
spec:
  selector:
    kubevirt.io/domain: vm-l2-a
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
  type: ClusterIP
